ZoneTell_ObjectPos(PlayerID player, ObjectID object, Vector3 pos)
ZoneTell_ObjectAll(PlayerID player, ObjectID object, Vector3 pos, Vector3 vel, float rot, ControlState state)
ZoneSays_ObjectEnter(ObjectID object)
ZoneSays_ObjectLeave(ObjectID object)
ZoneSays_ObjectClearClose(ObjectID object)
ZoneSays_ObjectsClose(ObjectID a, ObjectID b)
ZoneSays_ObjectAttach(ObjectID object, PlayerID player)
ZoneSays_ObjectPos(ObjectID object, Vector3 pos)
ZoneSays_ObjectAll(ObjectID object, Vector3 pos, Vector3 vel, float rot, ControlState state)
Player_RequestZoneSwitch(PlayerID player, ZoneID zone)
Player_EnterZone(PlayerID player, ZoneID zone)
Player_LeaveZone(PlayerID player, ZoneID zone)
Peer_RequestLogin(PeerID peer, const std::string& username, const MD5Hash& password)
Peer_RequestLogout(PeerID peer, PlayerID player)
Peer_LoginGranted(PeerID peer, PlayerID player)
Peer_LoginDenied(PeerID peer)
