ZoneEnter(PlayerID player, ZoneID zone)
ZoneLeave(PlayerID player, ZoneID zone)
ObjectState(ObjectID object, int flags)
ObjectPos(ObjectID object, Vector3 pos)
ObjectVel(ObjectID object, Vector3 vel)
ObjectRot(ObjectID object, Quaternion rot)
ObjectAssoc(ObjectID object, PlayerID player)
PlayerInput(PlayerID player, ControlState state)
PlayerRequestZoneSwitch(PlayerID player, ZoneID zone)
PeerRequestLogin(PeerID peer, const std::string& username, const MD5Hash& password)
PeerRequestLogout(PeerID peer, PlayerID player)
PeerLoginGranted(PeerID peer, PlayerID player)
PeerLoginDenied(PeerID peer)
