KeyExchange(uint64 key)
Login(string username, uint8 password[16])
Disconnect()
WhoIsPlayer(uint32 playerid)
PlayerInfo(uint32 playerid, string username)
PrivateMsg(uint32 playerid, string text)
BroadcastMsg(string text)
